### ISSUE TITLE
Self-Review: JavaScript Best Practices - To-do List Project

### ISSUE THREAD

**Issue by mavericksbalitaan** [mavericks-db/todo-list#5]
## Good Job 👍  in implementing the ff. JavaScript Best Practices: 💯 

- [x] Keep all the JavaScript code in JS files, not in the script tag.
- [x] Keep your [code clean](https://devinduct.com/blogpost/22/javascript-clean-code-best-practices) following this advice about:
- type checks `===` ✅ 
- descriptive variable and function naming ✅
- simplicity ✅ 
- the code is somewhat DRY but can still be improved ✅ 
- [x] .lock files are included in the repository to avoid problems with future versions of the dependencies.
- [x] Have used ES6 object destructuring to get the values from an object but can still be improved.

On the browser: 🌐 
- [x] No `console.log` found on the code
- [x] No `window.alert()` or `window.confirm()` found on the code
- [x] Keep the number of changes/updates to the DOM as low as possible, they are very expensive for the browser.
- [x] Keep the application logic separated from DOM manipulation tasks.
- [x] No `document.write` or `eval` 
- [x] Node_modules directory was added in the .gitignore file.
- [x] No old pieces of code as inline comments

---
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
