### ISSUE TITLE
Self-Review: HTML & CSS best practices - To-do List Project

### ISSUE THREAD

**Issue by mavericksbalitaan** [mavericks-db/todo-list#7]
## Good Job 👍 in implementing the ff. HTML & CSS Best Practices: 💯

- [x] Use the appropriate tags for each element (e.g., links, titles, etc.) and use HTML5 semantic tags (e.g., `header`, `nav`) over `div`s.
- [x] Avoid lines of code that are too long (100 characters or more).
- [x] Be careful with blank lines and indentation.
- Do not add blank lines, spaces, or indentations without a reason.
- For readability, add blank lines to separate large or logical code blocks.
- For readability, add two spaces of indentation. Do not use the tab key.
- [x] Close all HTML elements.
- [x] Use lowercase for elements and attribute names.
- [x] Always quote attribute values.
- [x] Use space-less equal signs.
- [x] Do not use inline styles. Keep your style definition in a separate CSS file.
- [x] Do not overuse `!important` rule in your CSS style definitions.
- [x] Always use the class attribute for multiple elements (do not use ID selector for multiple elements).
- [x] If you want to create a CSS rule for multiple elements, use a class attribute instead.
- [x] Do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

---
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
